version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      # whatever you’d normally export (e.g., DB creds)
      PYTHONUNBUFFERED: "1"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://backend:8000"
    depends_on:
      - backend
